kind: pipeline
name: default


steps:
  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: gcostigan/simple-app
      tags: latest
